# Generated by Django 5.2.7 on 2025-10-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_corpus_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
